apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashicat-web-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashicat-web
      version: v2
  template:
    metadata:
      labels:
        app: hashicat-web
        version: v2
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service-upstreams': 'hashicat-url:8080, hashicat-metadata:9080'
        'consul.hashicorp.com/service-tags': 'v2'
        'consul.hashicorp.com/service-meta-version': '2'
    spec:
      containers:
        - name: hashicat-web
          image: kawsark/hashicat-web:0.0.1
          imagePullPolicy: Always
          env:
            - name: DEBUG
              value: "True"
            - name: URLSERVICE_URI
              value: "http://127.0.0.1:8080"
            - name: METADATA_URI
              value: "http://127.0.0.1:9080"
          ports:
          - containerPort: 5000